MSTR-214: Validate list of space separated e911 email addresses
2600hz/monster-ui pull request #889
Opened 2021-02-12 20:56 UTC by azefiel

2021-02-15 18:03 UTC, guillegr123 requested changes

2021-02-15 18:03 UTC, guillegr123 commented on src/apps/core/i18n/en-US.json
> +				"one": "Please enter a valid email address.",
The e-mail rule seems to be broken when a single e-mail is validated:
![image](https://user-images.githubusercontent.com/893877/107980333-ab49b500-6f85-11eb-9db3-1a7b0022ba23.png)

2021-02-18 17:01 UTC, guillegr123 requested changes

2021-02-18 17:01 UTC, guillegr123 commented on src/js/lib/monster.ui.js
> +					_.partial(_.find, _.isString)
In this command, the first parameter for `lodash#find` needs to be the array to search over:
```suggestion
					_.partial(_.find, _, _.isString)
```

2021-02-18 19:12 UTC, azefiel commented on src/js/lib/monster.ui.js
> +						.value();
The stream was refactored so that path resolution happens before the truthy check (to avoid accessing the same path twice).

2021-02-19 05:31 UTC, guillegr123 approved these changes
Looks good to me!

2021-02-19 18:51 UTC, merged